FROM alpine:3.22.0

# Install system dependencies
RUN apk add --no-cache --update \
  python3 \
  py3-pip \
  gcc \
  musl-dev \
  python3-dev \
  libffi-dev \
  openssl-dev \
  cargo \
  make \
  bind-tools \
  net-tools \
  curl \
  openjdk21 \
  ca-certificates \
  lsb-release-minimal \
  docker \
  openrc \
  helm \
  zip \
  maven \
  bash \
  rsync \
  git \
  jq \
  nodejs

# Download cli tools
RUN curl -fsSLO https://github.com/Azure/kubelogin/releases/download/v0.1.5/kubelogin-linux-amd64.zip \
  && curl -fsSLO https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.2.1.4610.zip \
  && curl -fsSLO https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.32.0/allure-commandline-2.32.0.tgz

# Install cli tools
RUN unzip -ojd /usr/local/bin kubelogin-linux-amd64.zip bin/linux_amd64/kubelogin \
  && chmod +x /usr/local/bin/kubelogin \
  && unzip -qq sonar-scanner-cli-6.2.1.4610.zip \
  && mv sonar-scanner-6.2.1.4610 /opt/sonar-scanner-cli \
  && chmod +x /opt/sonar-scanner-cli/bin/sonar-scanner \
  && sed -i 's/use_embedded_jre=true/use_embedded_jre=false/g' /opt/sonar-scanner-cli/bin/sonar-scanner \
  && tar -xf allure-commandline-2.32.0.tgz \
  && mv allure-2.32.0 /opt/allure \
  && chmod -R +x /opt/allure/bin

# Create and activate a virtual environment for Azure CLI
RUN python3 -m venv /opt/venv \
  && . /opt/venv/bin/activate \
  && pip install --upgrade pip \
  && pip install --no-cache-dir azure-cli \
  && deactivate

# Clean up unnecessary build tools
RUN apk del \
  gcc \
  musl-dev \
  python3-dev \
  libffi-dev \
  openssl-dev \
  cargo \
  make \
  zip \
  && rm -rf /var/cache/apk/* \
  && rm -rf *.zip || true \
  && rm -rf *.tgz || true

# Update PATH to include the virtual environment
ENV PATH="/opt/allure/bin:/opt/sonar-scanner-cli/bin:/usr/local/bin:/opt/venv/bin:$PATH"

CMD ["sh"]
