apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pv-protection
  name: tscd5-react-home-log-live-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 15Gi
  mountOptions:
    - hard
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - sec=sys
  nfs:
    path: //ecmeu2aksvol002n/d5/home/live
    server: 172.25.79.72
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
