apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pv-protection
  name: tscprod-prd-log-live-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 15Gi
  mountOptions:
    - hard
    - nfsvers=4.1
    - rsize=262144
    - wsize=262144
    - sec=sys
  nfs:
    path: /tscsaecmcusp01/tscecmcusprdnfs005/prd/prod
    server: tscsaecmcusp01.privatelink.file.core.windows.net
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
