apiVersion: v1
kind: Service
metadata:
  name: failover-backup-svc
  namespace: ecom-svc-u2a
spec:
  externalName: tscu2b-searchsvc.ecom-svc-u2b.svc.cluster.local
  sessionAffinity: None
  type: ExternalName
