name: Run e2e tests for env
description: GitHub Action to run e2e tests for env

inputs:
  java_version:
    description: 'JAVA version'
    default: 21
  gh_user:
    description: 'GH_USER org secret'
    type: string
  gh_token:
    description: 'GH_TOKEN org secret'
    type: string
  catalog_dl_token:
    description: 'CATALOG_DL_TOKEN org secret'
    type: string
  e:
    description: 'Environment short name'
    type: string
  track:
    description: 'Track number'
    type: string
    default: ''

runs:
  using: "composite"
  steps:
    - name: Run e2e tests
      id: run-e2e-tests
      env:
        GH_USER: ${{ inputs.gh_user }}
        GH_TOKEN: ${{ inputs.gh_token }}
        DL_TOKEN: ${{ inputs.catalog_dl_token }}
        e: ${{ inputs.e}}
        track: ${{ inputs.track }}
      shell: bash
      run: ${GITHUB_ACTION_PATH}/e2e.sh
