apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
    - kubernetes.io/pv-protection
  name: tscproda-react-hom-log-live-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 15Gi
  mountOptions:
    - hard
    - nfsvers=4.1
    - rsize=262144
    - wsize=262144
    - sec=sys
  nfs:
    path: /tscsaecmeu2p01/tscecmeu2prdnfs004/proda/home/live
    server: tscsaecmeu2p01.privatelink.file.core.windows.net
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
