apiVersion: v1
kind: Service
metadata:
  name: failover-backup-svc
  namespace: ecom-svc-prod
spec:
  externalName: tscprodb-searchsvc.ecom-svc-prodb.svc.cluster.local
  sessionAffinity: None
  type: ExternalName
