apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pv-protection
  name: tscproddr-search-app-log-auth-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 15Gi
  mountOptions:
    - hard
    - nfsvers=4.1
    - rsize=262144
    - wsize=262144
    - sec=sys
  nfs:
    path: /ecmcusaksvol004p/proddr/search/auth
    server: 172.25.203.71
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
