apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: svc-u1-failover-vs
  namespace: ecom-svc-u1a
spec:
  host: priv-u1-src-srv-eu2.shop.tractorsupply.com
  routes:
  - path: /
    splits:
    - action:
        pass: primary-svc
      weight: 100
    - action:
        pass: secondary-svc
      weight: 0
  tls:
    secret: tscu1a-searchsvc
  upstreams:
  - name: primary-svc
    port: 8443
    service: tscu1a-searchsvc
    tls:
      enable: true
  - name: secondary-svc
    port: 8443
    service: failover-backup-svc
    tls:
      enable: true
