apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pv-protection
  name: tscd1-search-app-log-auth-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 15Gi
  mountOptions:
    - hard
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - sec=sys
  nfs:
    path: /ecmeu2aksvol004n/d1/search/auth
    server: 172.25.79.69
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
