# {{- if .Values.ingress.enabled }}
# apiVersion: v1
# data:
#   tls.crt: {{ $.Values.ingress.tls.crt | b64enc }}
#   tls.key: {{ $.Values.ingress.tls.key | b64enc }}
# kind: Secret
# metadata:
#   name: {{ $.Values.ingress.secretname }}
#   namespace: {{ $.Values.service.namespace }}
# type: kubernetes.io/tls
# {{- end }}