{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Values.service.environmentType }}-{{ .Values.service.environmentName }}-{{ .Chart.Name }}-ingress
  namespace: {{ .Values.service.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  labels:
    app: {{ $.Values.service.environmentType }}-{{ .Values.service.environmentName }}-{{ .Chart.Name }}
spec:
  ingressClassName: nginx-plus
  rules:
    - host: {{ $.Values.ingress.primaryHost }}
      http:
        paths:
          - backend:
              service:
                name: {{ $.Values.service.environmentType }}-{{ .Values.service.environmentName }}-{{ .Chart.Name }}
                port:
                  number: {{ $.Values.service.port }}
            path: /
            pathType: ImplementationSpecific
    - host: {{ $.Values.ingress.secondaryHost }}
      http:
        paths:
          - backend:
              service:
                name: {{ $.Values.service.environmentType }}-{{ .Values.service.environmentName }}-{{ .Chart.Name }}
                port:
                  number: {{ $.Values.service.port }}
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - {{ $.Values.ingress.primaryHost }}
        - {{ $.Values.ingress.secondaryHost }}
      secretName: {{ $.Values.ingress.secretname }}
  {{- end }}
