{{- if eq .Values.service.environmentType "auth" }}
  {{- if .Values.extraPersistentVolumeClaims.loggingAuthVolume.enabled | default false }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.service.tenant }}{{ .Values.service.environmentName }}-{{.Values.extraPersistentVolumeClaims.loggingAuthVolume.storageName}}"
spec:
  accessModes:
    - {{.Values.extraPersistentVolumeClaims.loggingAuthVolume.accessModes}}
  {{- if .Values.extraPersistentVolumeClaims.loggingAuthVolume.nfsEnabled }}
  storageClassName: ""
  volumeName: {{ .Values.service.tenant }}{{ .Values.service.environmentName }}-{{.Values.extraPersistentVolumeClaims.loggingAuthVolume.storageName}}
  {{- else }}
  storageClassName: {{.Values.extraPersistentVolumeClaims.loggingAuthVolume.storageClass}}
  {{- end }}
  resources:
    requests:
      storage: {{.Values.extraPersistentVolumeClaims.loggingAuthVolume.storageSize}}
    {{- end }}
  {{- end }}
  
  {{- if eq .Values.service.environmentType "live" }}
  {{- if .Values.extraPersistentVolumeClaims.loggingLiveVolume.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.service.tenant }}{{ .Values.service.environmentName }}-{{.Values.extraPersistentVolumeClaims.loggingLiveVolume.storageName}}"
spec:
  accessModes:
    - {{.Values.extraPersistentVolumeClaims.loggingLiveVolume.accessModes}}
  {{- if .Values.extraPersistentVolumeClaims.loggingLiveVolume.nfsEnabled }}
  storageClassName: ""
  volumeName: {{ .Values.service.tenant }}{{ .Values.service.environmentName }}-{{.Values.extraPersistentVolumeClaims.loggingLiveVolume.storageName}}
  {{- else }}
  storageClassName: {{.Values.extraPersistentVolumeClaims.loggingLiveVolume.storageClass}}
  {{- end }}
  resources:
    requests:
      storage: {{.Values.extraPersistentVolumeClaims.loggingLiveVolume.storageSize}}
  {{- end }}
  {{- end }}
