{{- if $.Values.splunk.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.splunk.sidecar_secret }}
  labels:
    app: splunk-otel-agent-secret
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "-" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  namespace: {{ .Values.service.namespace }}
type: Opaque
data:
  splunk_platform_hec_token: {{ .Values.splunk.token }}
{{- end }}
