name: Add Comment to the PR
description: GitHub Action to add Comment to the PR

inputs:
  comment_body:
    description: "Contents of the comment"
    required: true

runs:
  using: "composite"
  steps:
    - name: Add Comment to the PR
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request' || github.event_name == 'push'
      with:
        script: |
          const body = `${{ inputs.comment_body }}`;
          const { data: pull_requests } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
            owner: "${{ github.repository_owner }}",
            repo: "${{ github.event.repository.name }}",
            commit_sha: "${{ github.sha }}"
          });
          issue_number = context.issue.number;
          const merged_request = pull_requests.find((pull_request) => pull_request.state === 'closed');
          if (merged_request) issue_number = merged_request.number;
          if (issue_number !== "" && issue_number !== undefined && issue_number !== null) {
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number
            });
            const alreadyCommented = comments.some((comment) => comment.user.login === 'github-actions[bot]' && comment.body === body);
            if (!alreadyCommented) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                body: body
              });
            } else {
              console.log('Comment already added to this Pull Request.');
            }
          } else {
            console.log('Issue number was not find. Skipping this step.')
          }
