apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.service.namespace }}
  labels:
    app: {{ $.Values.service.environmentType }}-{{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "-" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "name" $ }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.service.replica }}
  selector:
    matchLabels:
      app: {{ $.Values.service.environmentType }}-{{ .Chart.Name }}
      chart: {{ .Chart.Name }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      app.kubernetes.io/name: {{ include "name" $ }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: {{ $.Values.service.environmentType }}{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ $.Values.service.environmentType }}-{{ .Chart.Name }}
        chart: {{ .Chart.Name }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        app.kubernetes.io/name: {{ include "name" $ }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: {{ $.Values.service.environmentType }}{{ .Chart.Name }}
        deploymentRevisionId: "{{ .Release.Revision }}" # this here updates and forces refresh
    spec:
      volumes:
      {{- if $.Values.extraPersistentVolumeClaims.dataloadVolume }}
      {{- if $.Values.extraPersistentVolumeClaims.dataloadVolume.enabled }}
        - name: "{{$.Values.extraPersistentVolumeClaims.dataloadVolume.storageName}}"
          persistentVolumeClaim:
            claimName: "{{$.Values.extraPersistentVolumeClaims.dataloadVolume.storageName}}"
      {{- end }}
      {{- end }}

      {{- if $.Values.extraPersistentVolumeClaims.dataloadLogVolume }}
      {{- if $.Values.extraPersistentVolumeClaims.dataloadLogVolume.enabled }}
        - name: "{{$.Values.extraPersistentVolumeClaims.dataloadLogVolume.storageName}}"
          persistentVolumeClaim:
            claimName: "{{$.Values.extraPersistentVolumeClaims.dataloadLogVolume.storageName}}"
      {{- end }}
      {{- end }}

      {{- if eq .Values.service.environmentType "live" }}
        {{- if $.Values.extraPersistentVolumeClaims.appLogLiveVolume }}
        {{- if $.Values.extraPersistentVolumeClaims.appLogLiveVolume.enabled }}
        - name: "{{$.Values.extraPersistentVolumeClaims.appLogLiveVolume.storageName}}"
          persistentVolumeClaim:
            claimName: "{{$.Values.extraPersistentVolumeClaims.appLogLiveVolume.storageName}}"
        {{- else }}
        - name: logs-sharing
          emptyDir: {}
        {{- end }}
        {{- end }}
      {{- end }}

  # splunk volume change
    {{- if $.Values.splunk.enable }}
      {{- if $.Values.splunk.sidecar_configmap }}
        - name: "{{ $.Values.splunk.sidecar_configmap }}"
          configMap:
            name: {{ $.Values.splunk.sidecar_configmap }}
      {{- end }}
        - name: checkpoint
          emptyDir: {}
    {{- end }}
## splunk volume changes end

      affinity:
        nodeAffinity:
          {{- if $.Values.service.nodeLabel }}
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - {{ $.Values.service.nodeLabel }}
          {{- else }}
          requiredDuringSchedulingIgnoredDuringExecution:
          {{- include "nodeAffinityRequiredDuringScheduling" $ | indent 8 }}
          {{- end }}
          preferredDuringSchedulingIgnoredDuringExecution:
          {{- include "nodeAffinityPreferredDuringScheduling" $ | indent 8 }}
      {{- include "service-podAntiAffinity" $ | indent 6 }}
      containers:
  ###### splunk code begins ######
{{- if $.Values.splunk.enable }}
      - name: splunk-otel-collector
        image: {{ $.Values.splunk.image }}:0.90.0
        {{- if $.Values.service.imagePullPolicy }}
        imagePullPolicy: {{ $.Values.service.imagePullPolicy }}
        {{- end }}
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: K8S_NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: K8S_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: K8S_POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: SPLUNK_PLATFORM_HEC_TOKEN
          valueFrom:
            secretKeyRef:
              key: splunk_platform_hec_token
              name: {{ $.Values.splunk.sidecar_secret }}
        - name: SPLUNK_MEMORY_TOTAL_MIB
          value: "{{ include "splunk-otel-collector.convertMemToMib" $.Values.splunk.resources.limits.memory }}"
        resources:
{{ toYaml $.Values.splunk.resources | indent 12 }}
        command:
        - /otelcol
        - --config=/conf/relay.conf
        securityContext:
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: false
          runAsNonRoot: false
          runAsUser: 0
          privileged: false
          capabilities:
            add:
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - KILL
            - SETGID
            - SETUID
            - SETPCAP
            - NET_BIND_SERVICE
            - NET_RAW
            - SYS_CHROOT
            - MKNOD
            - AUDIT_WRITE
            - SETFCAP
            drop:
            - all
        livenessProbe:
          initialDelaySeconds: 60
          failureThreshold: 3
          httpGet:
            path: /
            port: 13133
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          initialDelaySeconds: 60
          failureThreshold: 3
          httpGet:
            path: /
            port: 13133
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        {{- if eq .Values.service.environmentType "live" }}
          {{- if $.Values.extraPersistentVolumeClaims.appLogLiveVolume }}
          {{- if $.Values.extraPersistentVolumeClaims.appLogLiveVolume.enabled }}
          - name: "{{$.Values.extraPersistentVolumeClaims.appLogLiveVolume.storageName}}"
            mountPath: /app_logs
          {{- else }}
          - name: logs-sharing
            mountPath: /app_logs
          {{- end }}
          {{- end }}
          - name: "{{ $.Values.splunk.sidecar_configmap}}"
            mountPath: /conf
          - name: "{{ $.Values.splunk.checkpoint}}"
            mountPath: /var/addon/splunk/otel_pos
        {{- end }}
  {{- end }}
    ###### splunk code ends ######
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.registry }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ $.Values.service.imagePullPolicy }}
        resources:
          {{- toYaml $.Values.service.resources | nindent 12 }}
        env:
        - name: "ENVIRONMENT"
          value: {{ $.Values.service.environmentName | quote }}
        - name: "TZ"
          value: {{ $.Values.service.timezone | quote }}
        - name: "TENANT"
          value: {{$.Values.service.tenant | quote }}
        - name: "CONFIG_SERVER_URL"
          value: {{ $.Values.service.configSrvUrl | quote }}
        - name: "CLOUD_CONFIG_BRANCH"
          value: {{ $.Values.service.cloudConfigBranch | quote }}
        - name: "CLOUD_CONFIG_ENABLED"
          value: {{ $.Values.service.cloudConfigEnabled | quote }}
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: AZURE_VAULT_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: azure-vault-client-secret
              key: client-secret
        - name: AZURE_VAULT_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: azure-vault-client-id
              key: client-id
        - name: AZURE_VAULT_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: azure-vault-client-secret
              key: client-secret
        - name: AZURE_VAULT_URL
          valueFrom:
            secretKeyRef:
              name: azure-vault-url
              key: vault-url
        - name: AZURE_VAULT_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: azure-vault-tenant-id
              key: tenant-id
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 120
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 120
          successThreshold: 1
          failureThreshold: 20
        securityContext:
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: false
          runAsNonRoot: false
          runAsUser: 0
          privileged: false
          capabilities:
            drop:
            - all
            add:
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - KILL
            - SETGID
            - SETUID
            - SETPCAP
            - NET_BIND_SERVICE
            - NET_RAW
            - SYS_CHROOT
            - MKNOD
            - AUDIT_WRITE
            - SETFCAP
        volumeMounts:
        {{- if $.Values.extraPersistentVolumeClaims.dataloadVolume }}
        {{- if $.Values.extraPersistentVolumeClaims.dataloadVolume.enabled }}
          - name: "{{$.Values.extraPersistentVolumeClaims.dataloadVolume.storageName}}"
            mountPath: {{ $.Values.extraPersistentVolumeClaims.dataloadVolume.mountPath }}
        {{- end }}
        {{- end }}
        
        {{- if $.Values.extraPersistentVolumeClaims.dataloadLogVolume }}
        {{- if $.Values.extraPersistentVolumeClaims.dataloadLogVolume.enabled }}
          - name: "{{$.Values.extraPersistentVolumeClaims.dataloadLogVolume.storageName}}"
            mountPath: {{ $.Values.extraPersistentVolumeClaims.dataloadLogVolume.mountPath }}
        {{- end }}
        {{- end }}

        {{- if eq .Values.service.environmentType "live" }}
          {{- if $.Values.extraPersistentVolumeClaims.appLogLiveVolume }}
          {{- if $.Values.extraPersistentVolumeClaims.appLogLiveVolume.enabled }}
          - name: "{{$.Values.extraPersistentVolumeClaims.appLogLiveVolume.storageName}}"
            mountPath: {{ $.Values.extraPersistentVolumeClaims.appLogLiveVolume.mountPath }}
          {{- else }}
          - name: logs-sharing
            mountPath: /app/logs
          {{- end }}
          {{- end }}
        {{- end }}
