name: Download file from Azure Blob Container
description: Download file from Azure Blob Container

inputs:
  gh_user:
    description: 'GH_USER org secret'
    type: string
  gh_token:
    description: 'GH_TOKEN org secret'
    type: string
  azure_client_id:
    description: 'AZURE_CLIENT_ID org secret'
    type: string
  azure_client_secret:
    description: 'AZURE_CLIENT_SECRET org secret'
    type: string
  azure_tenant_id:
    description: 'AZURE_TENANT_ID org secret'
    type: string
  file_path: 
    description: 'Where to put the file?'
    type: string
  file_name: 
    description: 'File name?'
    type: string
  storage_account: 
    description: 'Storage account name'
    type: string
  blob_container: 
    description: 'Blob container name'
    type: string

runs:
  using: "composite"
  steps:
    - name: Download file from Blob Container
      env:
        GH_USER: ${{ inputs.gh_user }}
        GH_TOKEN: ${{ inputs.gh_token }}
        AZURE_CLIENT_ID: ${{ inputs.azure_client_id }}
        AZURE_CLIENT_SECRET: ${{ inputs.azure_client_secret }}
        AZURE_TENANT_ID: ${{ inputs.azure_tenant_id }}
        FILE_PATH: ${{ inputs.file_path }}
        FILE_NAME: ${{ inputs.file_name }}
        STORAGE_ACCOUNT: ${{ inputs.storage_account }}
        BLOB_CONTAINER: ${{ inputs.blob_container }}
      shell: bash
      run: ${GITHUB_ACTION_PATH}/script.sh
